### ISSUE TITLE
MOA sizeofag not calculate memory measure

### ISSUE THREAD

**Issue by asm123955** [fracpete/sizeofag#1]
Hello 
when run moa to concept drift tab to result from dataset
the memory measure is not calculated as indicated in image attached
can please help me 

also, i have this message in running output
Can not access instrumentation environment.
Please check if jar file containing SizeOfAgent class is 
specified in the java's "-javaagent" command line argument.

![2021 7 output - memory](https://user-images.githubusercontent.com/57035015/165169116-fcfec042-47d0-4194-be87-ed14ac97c5d6.PNG)

**Comment by fracpete** [comment]
Check the batch file/shell script in the `bin` directory of a MOA release or snapshot to see how to include the sizeofag jar file to enable the memory calculation. Based on the error message, your command for launching the JVM does not seem to include it (or is using a wrong path).

**Comment by asm123955** [comment]
many thanks for reply 
I checked it and attach a screenshot of it.
Is it correct or what I can do to work it 
wait for response please 

![moa bat](https://user-images.githubusercontent.com/57035015/165183746-56521f00-57e5-49e1-a42c-56f31a7702fc.PNG)

![moa](https://user-images.githubusercontent.com/57035015/165183791-1e88a5ac-f661-450f-8801-191eec25bfaf.PNG)

![moa sh](https://user-images.githubusercontent.com/57035015/165183804-e4b46257-73a9-4a6f-83c0-6c998b3f6263.PNG)

**Comment by fracpete** [comment]
You haven't posted how you are launching your application (and under what OS), nor where your sizeofag jar is located.

**Comment by asm123955** [comment]
I am using windows 10. 
sizeofag  under dependencies in MOA folder as seen 

![MOA netbeans](https://user-images.githubusercontent.com/57035015/165185652-254a2245-ff6f-4bfb-8064-14423e7b4f32.PNG)

**Comment by fracpete** [comment]
So you are using an IDE to launch MOA and not the provided batch/shell scripts.

For simplicity, use the absolute path (using **forward** slashes!) to the sizeofag jar for the `-javaagent` parameter of your JVM launch configuration, similar to the Windows batch file that comes with MOA.

I'm not familiar with NetBeans, so you will have to figure out yourself where to pass parameters to the JVM.

**Comment by asm123955** [comment]
Sorry I do not understand well, how to pass parameter
I am new to use MOA

**Comment by fracpete** [comment]
In NetBeans, you can specify JVM parameters for your Run configurations, e.g.:

![config](https://user-images.githubusercontent.com/1026180/165189128-a6762d7e-fc10-41ce-836f-ebb0dfdc94dd.png)

**Comment by asm123955** [comment]
many thanks for your efforts 
yes, I run this before but i have an exception attached
![config](https://user-images.githubusercontent.com/57035015/165190972-d201ab29-2c34-4774-94d2-639d141305c1.PNG)
![config_error](https://user-images.githubusercontent.com/57035015/165190982-a7cc0db7-7de1-4f11-8efe-dba1038c1ece.PNG)

**Comment by fracpete** [comment]
Check your specification vs what is used in `moa.bat`, which you posted a screenshot of earlier.

Some hints: 
- Are you using forward slashes?
- Spaces usually indicate separate options. What is used to avoid that?

**Comment by asm123955** [comment]
Iam try these 3 commands in vm option but failed with errors
-javaagent:C:/Users\Eng Asmaa\.m2\repository\com\github\fracpete\sizeofag\1.0.4\sizeofag-1.0.4.jar

-javaagent:C:/Users/Eng Asmaa/.m2/repository/com/github/fracpete/sizeofag/1.0.4/sizeofag-1.0.4.jar

Asmaa/.m2/repository/com/github/fracpete/sizeofag/1.0.4/sizeofag-1.0.4.jar  -javaagent:C:/Users/Eng 


give me these errors in run 
what can you recommend me i do now

-- exec-maven-plugin:3.0.0:exec (default-cli) @ moa ---
Error opening zip file or JAR manifest missing : Users/Eng/Asmaa/.m2/repository/com/github/fracpete/sizeofag/1.0.4/sizeofag-1.0.4.jar
Error occurred during initialization of VM
agent library failed to init: instrument
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  2.171 s
Finished at: 2022-04-26T05:05:09+02:00
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project moa: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by fracpete** [comment]
Two things: 
* You have a space in your path, therefore you need to quote the file with double quotes (like in `moa.bat` as I hinted at)
* Does that jar file actually exist? What I screenshotted was an example on **my** computer. You have to adjust that path, of course (I don't know where your files are located).

**Comment by asm123955** [comment]
Can you send me your mail to contact your remotely to see it 
as I try more but not solved

**Comment by asm123955** [comment]
I wait for response please 

many many thanks for your help to me

**Comment by fracpete** [comment]
No private tutoring.

Before trying to get things going in your IDE, try getting things to work from the command-line.

Determine:
* absolute path to your MOA directory (the one that contains the `bin` and `lib` directories)
* absolute path to the sizeofag jar file (which resides inside the `lib` dir)

Then you can start up MOA from the command-prompt like this (replacing the <...> placeholders with the appropriate paths, using **forward** slashes and not backslashes what Windows normally uses):
```
java -cp "<MOADIR>/lib/*" -javaagent:"<SIZEOFAGFILE>" moa.gui.GUI
```

Once confirmed that the memory calculation is working when starting MOA like this, you can use the `-javaagent ...` part in your IDE.

**Comment by asm123955** [comment]
Hello, I wait for your response to, please Many thanks in advance 
    On Wednesday, April 27, 2022, 01:11:50 AM GMT+2, Peter Reutemann ***@***.***> wrote:  
 
 


No private tutoring.

Before trying to get things going in your IDE, try getting things to work from the command-line.

Determine:
   
   - absolute path to your MOA directory (the one that contains the bin and lib directories)
   - absolute path to the sizeofag jar file (which resides inside the lib dir)

Then you can start up MOA from the command-prompt like this (replacing the <...> placeholders with the appropriate paths, using forward slashes and not backslashes what Windows normally uses):
java -cp "<MOADIR>/lib/*" -javaagent:"<SIZEOFAGFILE>" moa.gui.GUI

Once confirmed that the memory calculation is working when starting MOA like this, you can use the -javaagent ... part in your IDE.

**Comment by asm123955** [comment]
I try more but not work 
can I send you app compressed file to see it please

**Comment by fracpete** [comment]
Did you follow the instructions in [my response](https://github.com/fracpete/sizeofag/issues/1#issuecomment-1110333822)? What are the paths and what was the outcome?

**Comment by asm123955** [comment]
this error after determine jar file 


![2017 errors](https://user-images.githubusercontent.com/57035015/167226176-53b2c691-a852-4e69-aa69-e9b88171e26b.PNG)

**Comment by fracpete** [comment]
Your path contains spaces, therefore must be enclosed in double quotes. I've said that already before.

**Comment by asm123955** [comment]
When I counter full path with double-quote as I attached it gives me an error as incorrect syntax
The space in the path is really the name of the folder containing the space. I just copy the real path and does not modify on it
![2017 errors2](https://user-images.githubusercontent.com/57035015/167271452-efc128ca-b8d5-42ef-adab-acf80261a170.PNG)

**Comment by asm123955** [comment]
hello, 
I wait for response please, many thanks in advance

**Comment by fracpete** [comment]
[I have work to do as well, so answers can take a while.]

Surround all of the command, not just the path with double quotes, i.e.: `"-javaagent:..."`

![moa](https://user-images.githubusercontent.com/1026180/167745728-bef21838-63ec-4ecf-8363-96494ab40534.png)

**Comment by asm123955** [comment]
Yes, it work many thanks
