### ISSUE TITLE
SizeOfAgent.fullSizeOf("This is a long string") returns zero

### ISSUE THREAD

**Issue by Yaytay** [fracpete/sizeofag#3]
SizeOfAgent.fullSizeOf is working correctly for a bunch of types, but for strings I'm always getting a value of 0.

Using Zulu JDK 21 on 64 bit Windows.

Thanks

**Comment by fracpete** [comment]
The String class maintains an internal pool of String objects for optimization reasons. Such strings won't get counted, explaining why you see 0. See [String.intern()](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#intern--).

**Comment by fracpete** [comment]
I've updated the examples which shows that the size isn't always 0 for strings, basically when the pool  of internal strings gets exhausted:

https://github.com/fracpete/sizeofag?tab=readme-ov-file#total-size

**Comment by Yaytay** [comment]
Thanks, makes sense.
